In [1]:
import pandas as pd

In [3]:
original_metadata = pd.read_csv("../../processed_meta_full.csv")

In [4]:
original_metadata.head()

,original_image_name,orig_dataset,label,mha,Finding Labels,Patient ID,Patient Age,Patient Gender,original_image_width,original_image_height,...,orig_bbox_height,shared_image_width,shared_image_height,Study Year,Manufacturer,Modality,subtlety,nodule_size,malignant,Partition
0,00010496_001,chestxray14,1,n0239.mha,Nodule,10496,44.0,M,2992.0,2991.0,...,94,1024,1024,NaN,NaN,NaN,NaN,NaN,NaN,Train
1,00006281_000,chestxray14,1,n0342.mha,Nodule,6281,46.0,F,2500.0,2048.0,...,40,1024,1024,NaN,NaN,NaN,NaN,NaN,NaN,Train
2,00001404_000,chestxray14,1,n0996.mha,Nodule,1404,47.0,M,2048.0,2500.0,...,108,1024,1024,NaN,NaN,NaN,NaN,NaN,NaN,Test
3,00029196_000,chestxray14,1,n0418.mha,Nodule,29196,48.0,F,2021.0,2021.0,...,75,1024,1024,NaN,NaN,NaN,NaN,NaN,NaN,Train
4,00014646_003,chestxray14,1,n0538.mha,Nodule,14646,55.0,M,2992.0,2991.0,...,69,1024,1024,NaN,NaN,NaN,NaN,NaN,NaN,Train

In [10]:
original_metadata['dir_name'] = original_metadata['mha'].apply(lambda x: x.split(".")[0])

In [11]:
mapping_df = original_metadata[['dir_name','orig_dataset']]

In [13]:
mapping_df.head()

  dir_name orig_dataset
0    n0239  chestxray14
1    n0342  chestxray14
2    n0996  chestxray14
3    n0418  chestxray14
4    n0538  chestxray14

In [24]:
mapping_df.to_csv("../split_node21_sets/mapping.csv",index=False)

In [17]:
!cp ../split_node21/arch_seg.zip ../split_node21_sets/

In [22]:
!unzip ../split_node21_sets/arch_seg.zip -d ../split_node21_sets/

Archive:  ../split_node21_sets/arch_seg.zip
   creating: ../split_node21_sets/arch_seg/
  inflating: ../split_node21_sets/arch_seg/.DS_Store
  inflating: ../split_node21_sets/__MACOSX/arch_seg/._.DS_Store
   creating: ../split_node21_sets/arch_seg/test/
   creating: ../split_node21_sets/arch_seg/train/
  inflating: ../split_node21_sets/arch_seg/test/.DS_Store
  inflating: ../split_node21_sets/__MACOSX/arch_seg/test/._.DS_Store
  inflating: ../split_node21_sets/arch_seg/test/process_log.csv
   creating: ../split_node21_sets/arch_seg/test/nodule/
   creating: ../split_node21_sets/arch_seg/test/normal/
  inflating: ../split_node21_sets/arch_seg/train/.DS_Store
  inflating: ../split_node21_sets/__MACOSX/arch_seg/train/._.DS_Store
  inflating: ../split_node21_sets/arch_seg/train/process_log.csv
   creating: ../split_node21_sets/arch_seg/train/nodule/
   creating: ../split_node21_sets/arch_seg/train/normal/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0198/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0154/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0957/
  inflating: ../split_node21_sets/__MACOSX/arch_seg/test/nodule/._n0957
   creating: ../split_node21_sets/arch_seg/test/nodule/n0734/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0357/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1043/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1088/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0758/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0935/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0109/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1010/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0794/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0760/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0903/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0564/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0904/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0563/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0107/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0597/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1042/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0958/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0732/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0500/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0993/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0507/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0538/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0367/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0703/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0358/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1074/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0394/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0704/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0199/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0902/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0101/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1027/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0108/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0305/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1011/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1029/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0759/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0933/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0130/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0614/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0042/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0089/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0045/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0277/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0428/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0246/
  inflating: ../split_node21_sets/arch_seg/test/nodule/.DS_Store
  inflating: ../split_node21_sets/__MACOSX/arch_seg/test/nodule/._.DS_Store
   creating: ../split_node21_sets/arch_seg/test/nodule/n0622/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0279/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0020/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0444/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0682/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0824/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0027/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0678/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0029/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1130/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0075/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0849/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0411/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0278/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0876/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0240/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0072/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0429/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0885/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0847/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0285/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0427/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0271/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0088/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0225/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0825/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0489/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0442/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0026/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1100/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0684/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1107/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0021/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0493/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0800/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0838/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1122/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1114/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0469/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0809/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0207/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0663/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0253/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0059/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0891/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0853/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0050/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0434/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0601/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0206/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0808/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0837/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0691/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0830/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1123/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1124/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0801/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0855/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0432/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0056/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0852/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0297/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0051/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0864/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0093/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0299/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0060/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0404/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0582/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0576/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0911/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0929/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0916/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0318/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0547/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0311/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0123/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0781/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0920/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0578/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0772/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0927/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1069/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0514/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0980/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0513/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0177/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0942/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0141/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0373/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0717/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0989/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1067/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0945/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0380/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0522/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0374/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1094/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0146/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0125/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0541/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0773/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0787/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0780/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0546/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1032/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0570/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0789/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0321/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0944/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1095/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1059/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0988/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0372/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0716/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0149/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0182/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0176/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0718/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0972/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0388/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0338/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1013/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0931/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0556/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0764/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0567/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0998/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0396/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0739/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1049/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0166/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0730/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0192/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1047/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1078/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0962/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0105/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0568/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0550/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0306/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0908/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1012/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0709/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0399/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1041/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0707/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1048/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0952/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0532/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0955/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0169/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0686/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0440/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0818/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0216/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0820/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0688/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0643/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0227/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0015/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0485/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0449/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0482/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0280/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0274/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0046/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0041/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0273/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0287/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0880/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0084/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0414/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0070/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0289/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0619/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1132/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0470/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0828/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0014/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0821/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1104/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0210/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0441/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0627/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0071/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0872/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0618/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0886/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0412/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0881/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0286/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0424/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0040/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0281/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0091/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0062/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0868/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0261/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0053/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0651/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0804/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0490/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0452/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0660/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0009/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0667/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0455/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0031/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1117/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0409/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0436/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0856/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0431/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0894/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0893/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0632/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0256/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0692/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0030/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1129/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0233/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1118/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1120/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0462/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0805/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0510/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0346/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0948/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0180/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0341/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0946/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0383/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0713/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0941/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0189/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0142/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1090/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0526/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0714/
  inflating: ../split_node21_sets/__MACOSX/arch_seg/test/nodule/._n0714
   creating: ../split_node21_sets/arch_seg/test/nodule/n0740/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0129/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0581/
  inflating: ../split_node21_sets/__MACOSX/arch_seg/test/nodule/._n0581
   creating: ../split_node21_sets/arch_seg/test/nodule/n0543/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0924/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0544/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0518/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0940/
   creating: ../split_node21_sets/arch_seg/test/nodule/n1096/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0382/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0340/
   creating: ../split_node21_sets/arch_seg/test/nodule/n0172/

In [29]:
!unzip ../split_node21/crop.zip -d ../split_node21_sets/

Archive:  ../split_node21/crop.zip
   creating: ../split_node21_sets/crop/
  inflating: ../split_node21_sets/crop/.DS_Store
  inflating: ../split_node21_sets/__MACOSX/crop/._.DS_Store
   creating: ../split_node21_sets/crop/test/
   creating: ../split_node21_sets/crop/train/
  inflating: ../split_node21_sets/crop/test/.DS_Store
  inflating: ../split_node21_sets/__MACOSX/crop/test/._.DS_Store
  inflating: ../split_node21_sets/crop/test/process_log.csv
   creating: ../split_node21_sets/crop/test/nodule/
   creating: ../split_node21_sets/crop/test/normal/
  inflating: ../split_node21_sets/crop/train/.DS_Store
  inflating: ../split_node21_sets/__MACOSX/crop/train/._.DS_Store
  inflating: ../split_node21_sets/crop/train/process_log.csv
   creating: ../split_node21_sets/crop/train/nodule/
   creating: ../split_node21_sets/crop/train/normal/
   creating: ../split_node21_sets/crop/test/nodule/n0198/
   creating: ../split_node21_sets/crop/test/nodule/n0154/
   creating: ../split_node21_sets/crop/test/nodule/n0957/
   creating: ../split_node21_sets/crop/test/nodule/n0734/
   creating: ../split_node21_sets/crop/test/nodule/n0357/
   creating: ../split_node21_sets/crop/test/nodule/n1043/
   creating: ../split_node21_sets/crop/test/nodule/n1088/
   creating: ../split_node21_sets/crop/test/nodule/n0758/
   creating: ../split_node21_sets/crop/test/nodule/n0935/
   creating: ../split_node21_sets/crop/test/nodule/n0109/
   creating: ../split_node21_sets/crop/test/nodule/n1010/
   creating: ../split_node21_sets/crop/test/nodule/n0794/
   creating: ../split_node21_sets/crop/test/nodule/n0760/
   creating: ../split_node21_sets/crop/test/nodule/n0903/
   creating: ../split_node21_sets/crop/test/nodule/n0564/
   creating: ../split_node21_sets/crop/test/nodule/n0904/
   creating: ../split_node21_sets/crop/test/nodule/n0563/
   creating: ../split_node21_sets/crop/test/nodule/n0107/
   creating: ../split_node21_sets/crop/test/nodule/n0597/
   creating: ../split_node21_sets/crop/test/nodule/n1042/
   creating: ../split_node21_sets/crop/test/nodule/n0958/
   creating: ../split_node21_sets/crop/test/nodule/n0732/
   creating: ../split_node21_sets/crop/test/nodule/n0500/
   creating: ../split_node21_sets/crop/test/nodule/n0993/
   creating: ../split_node21_sets/crop/test/nodule/n0507/
   creating: ../split_node21_sets/crop/test/nodule/n0538/
   creating: ../split_node21_sets/crop/test/nodule/n0367/
   creating: ../split_node21_sets/crop/test/nodule/n0703/
   creating: ../split_node21_sets/crop/test/nodule/n0358/
   creating: ../split_node21_sets/crop/test/nodule/n1074/
   creating: ../split_node21_sets/crop/test/nodule/n0394/
   creating: ../split_node21_sets/crop/test/nodule/n0704/
   creating: ../split_node21_sets/crop/test/nodule/n0199/
   creating: ../split_node21_sets/crop/test/nodule/n0902/
   creating: ../split_node21_sets/crop/test/nodule/n0101/
   creating: ../split_node21_sets/crop/test/nodule/n1027/
   creating: ../split_node21_sets/crop/test/nodule/n0108/
   creating: ../split_node21_sets/crop/test/nodule/n0305/
   creating: ../split_node21_sets/crop/test/nodule/n1011/
   creating: ../split_node21_sets/crop/test/nodule/n1029/
   creating: ../split_node21_sets/crop/test/nodule/n0759/
   creating: ../split_node21_sets/crop/test/nodule/n0933/
   creating: ../split_node21_sets/crop/test/nodule/n0130/
   creating: ../split_node21_sets/crop/test/nodule/n0614/
   creating: ../split_node21_sets/crop/test/nodule/n0042/
   creating: ../split_node21_sets/crop/test/nodule/n0089/
   creating: ../split_node21_sets/crop/test/nodule/n0045/
   creating: ../split_node21_sets/crop/test/nodule/n0277/
   creating: ../split_node21_sets/crop/test/nodule/n0428/
   creating: ../split_node21_sets/crop/test/nodule/n0246/
  inflating: ../split_node21_sets/crop/test/nodule/.DS_Store
  inflating: ../split_node21_sets/__MACOSX/crop/test/nodule/._.DS_Store
   creating: ../split_node21_sets/crop/test/nodule/n0622/
   creating: ../split_node21_sets/crop/test/nodule/n0279/
   creating: ../split_node21_sets/crop/test/nodule/n0020/
   creating: ../split_node21_sets/crop/test/nodule/n0444/
   creating: ../split_node21_sets/crop/test/nodule/n0682/
   creating: ../split_node21_sets/crop/test/nodule/n0824/
   creating: ../split_node21_sets/crop/test/nodule/n0027/
   creating: ../split_node21_sets/crop/test/nodule/n0678/
   creating: ../split_node21_sets/crop/test/nodule/n0029/
   creating: ../split_node21_sets/crop/test/nodule/n1130/
   creating: ../split_node21_sets/crop/test/nodule/n0075/
   creating: ../split_node21_sets/crop/test/nodule/n0849/
   creating: ../split_node21_sets/crop/test/nodule/n0411/
   creating: ../split_node21_sets/crop/test/nodule/n0278/
   creating: ../split_node21_sets/crop/test/nodule/n0876/
   creating: ../split_node21_sets/crop/test/nodule/n0240/
   creating: ../split_node21_sets/crop/test/nodule/n0072/
   creating: ../split_node21_sets/crop/test/nodule/n0429/
   creating: ../split_node21_sets/crop/test/nodule/n0885/
   creating: ../split_node21_sets/crop/test/nodule/n0847/
   creating: ../split_node21_sets/crop/test/nodule/n0285/
   creating: ../split_node21_sets/crop/test/nodule/n0427/
   creating: ../split_node21_sets/crop/test/nodule/n0271/
   creating: ../split_node21_sets/crop/test/nodule/n0088/
   creating: ../split_node21_sets/crop/test/nodule/n0225/
   creating: ../split_node21_sets/crop/test/nodule/n0825/
   creating: ../split_node21_sets/crop/test/nodule/n0489/
   creating: ../split_node21_sets/crop/test/nodule/n0442/
   creating: ../split_node21_sets/crop/test/nodule/n0026/
   creating: ../split_node21_sets/crop/test/nodule/n1100/
   creating: ../split_node21_sets/crop/test/nodule/n0684/
   creating: ../split_node21_sets/crop/test/nodule/n1107/
   creating: ../split_node21_sets/crop/test/nodule/n0021/
   creating: ../split_node21_sets/crop/test/nodule/n0493/
   creating: ../split_node21_sets/crop/test/nodule/n0800/
   creating: ../split_node21_sets/crop/test/nodule/n0838/
   creating: ../split_node21_sets/crop/test/nodule/n1122/
   creating: ../split_node21_sets/crop/test/nodule/n1114/
   creating: ../split_node21_sets/crop/test/nodule/n0469/
   creating: ../split_node21_sets/crop/test/nodule/n0809/
   creating: ../split_node21_sets/crop/test/nodule/n0207/
   creating: ../split_node21_sets/crop/test/nodule/n0663/
   creating: ../split_node21_sets/crop/test/nodule/n0253/
   creating: ../split_node21_sets/crop/test/nodule/n0059/
   creating: ../split_node21_sets/crop/test/nodule/n0891/
   creating: ../split_node21_sets/crop/test/nodule/n0853/
   creating: ../split_node21_sets/crop/test/nodule/n0050/
   creating: ../split_node21_sets/crop/test/nodule/n0434/
   creating: ../split_node21_sets/crop/test/nodule/n0601/
   creating: ../split_node21_sets/crop/test/nodule/n0206/
   creating: ../split_node21_sets/crop/test/nodule/n0808/
   creating: ../split_node21_sets/crop/test/nodule/n0837/
   creating: ../split_node21_sets/crop/test/nodule/n0691/
   creating: ../split_node21_sets/crop/test/nodule/n0830/
   creating: ../split_node21_sets/crop/test/nodule/n1123/
   creating: ../split_node21_sets/crop/test/nodule/n1124/
   creating: ../split_node21_sets/crop/test/nodule/n0801/
   creating: ../split_node21_sets/crop/test/nodule/n0855/
   creating: ../split_node21_sets/crop/test/nodule/n0432/
   creating: ../split_node21_sets/crop/test/nodule/n0056/
   creating: ../split_node21_sets/crop/test/nodule/n0852/
   creating: ../split_node21_sets/crop/test/nodule/n0297/
   creating: ../split_node21_sets/crop/test/nodule/n0051/
   creating: ../split_node21_sets/crop/test/nodule/n0864/
   creating: ../split_node21_sets/crop/test/nodule/n0093/
   creating: ../split_node21_sets/crop/test/nodule/n0299/
   creating: ../split_node21_sets/crop/test/nodule/n0060/
   creating: ../split_node21_sets/crop/test/nodule/n0404/
   creating: ../split_node21_sets/crop/test/nodule/n0582/
   creating: ../split_node21_sets/crop/test/nodule/n0576/
   creating: ../split_node21_sets/crop/test/nodule/n0911/
   creating: ../split_node21_sets/crop/test/nodule/n0929/
   creating: ../split_node21_sets/crop/test/nodule/n0916/
   creating: ../split_node21_sets/crop/test/nodule/n0318/
   creating: ../split_node21_sets/crop/test/nodule/n0547/
   creating: ../split_node21_sets/crop/test/nodule/n0311/
   creating: ../split_node21_sets/crop/test/nodule/n0123/
   creating: ../split_node21_sets/crop/test/nodule/n0781/
   creating: ../split_node21_sets/crop/test/nodule/n0920/
   creating: ../split_node21_sets/crop/test/nodule/n0578/
   creating: ../split_node21_sets/crop/test/nodule/n0772/
   creating: ../split_node21_sets/crop/test/nodule/n0927/
   creating: ../split_node21_sets/crop/test/nodule/n1069/
   creating: ../split_node21_sets/crop/test/nodule/n0514/
   creating: ../split_node21_sets/crop/test/nodule/n0980/
   creating: ../split_node21_sets/crop/test/nodule/n0513/
   creating: ../split_node21_sets/crop/test/nodule/n0177/
   creating: ../split_node21_sets/crop/test/nodule/n0942/
   creating: ../split_node21_sets/crop/test/nodule/n0141/
   creating: ../split_node21_sets/crop/test/nodule/n0373/
   creating: ../split_node21_sets/crop/test/nodule/n0717/
   creating: ../split_node21_sets/crop/test/nodule/n0989/
   creating: ../split_node21_sets/crop/test/nodule/n1067/
   creating: ../split_node21_sets/crop/test/nodule/n0945/
   creating: ../split_node21_sets/crop/test/nodule/n0380/
   creating: ../split_node21_sets/crop/test/nodule/n0522/
   creating: ../split_node21_sets/crop/test/nodule/n0374/
   creating: ../split_node21_sets/crop/test/nodule/n1094/
   creating: ../split_node21_sets/crop/test/nodule/n0146/
   creating: ../split_node21_sets/crop/test/nodule/n0125/
   creating: ../split_node21_sets/crop/test/nodule/n0541/
   creating: ../split_node21_sets/crop/test/nodule/n0773/
   creating: ../split_node21_sets/crop/test/nodule/n0787/
   creating: ../split_node21_sets/crop/test/nodule/n0780/
   creating: ../split_node21_sets/crop/test/nodule/n0546/
   creating: ../split_node21_sets/crop/test/nodule/n1032/
   creating: ../split_node21_sets/crop/test/nodule/n0570/
   creating: ../split_node21_sets/crop/test/nodule/n0789/
   creating: ../split_node21_sets/crop/test/nodule/n0321/
   creating: ../split_node21_sets/crop/test/nodule/n0944/
   creating: ../split_node21_sets/crop/test/nodule/n1095/
   creating: ../split_node21_sets/crop/test/nodule/n1059/
   creating: ../split_node21_sets/crop/test/nodule/n0988/
   creating: ../split_node21_sets/crop/test/nodule/n0372/
   creating: ../split_node21_sets/crop/test/nodule/n0716/
   creating: ../split_node21_sets/crop/test/nodule/n0149/
   creating: ../split_node21_sets/crop/test/nodule/n0182/
   creating: ../split_node21_sets/crop/test/nodule/n0176/
   creating: ../split_node21_sets/crop/test/nodule/n0718/
   creating: ../split_node21_sets/crop/test/nodule/n0972/
   creating: ../split_node21_sets/crop/test/nodule/n0388/
   creating: ../split_node21_sets/crop/test/nodule/n0338/
   creating: ../split_node21_sets/crop/test/nodule/n1013/
   creating: ../split_node21_sets/crop/test/nodule/n0931/
   creating: ../split_node21_sets/crop/test/nodule/n0556/
   creating: ../split_node21_sets/crop/test/nodule/n0764/
   creating: ../split_node21_sets/crop/test/nodule/n0567/
   creating: ../split_node21_sets/crop/test/nodule/n0998/
   creating: ../split_node21_sets/crop/test/nodule/n0396/
   creating: ../split_node21_sets/crop/test/nodule/n0739/
   creating: ../split_node21_sets/crop/test/nodule/n1049/
   creating: ../split_node21_sets/crop/test/nodule/n0166/
   creating: ../split_node21_sets/crop/test/nodule/n0730/
   creating: ../split_node21_sets/crop/test/nodule/n0192/
   creating: ../split_node21_sets/crop/test/nodule/n1047/
   creating: ../split_node21_sets/crop/test/nodule/n1078/
   creating: ../split_node21_sets/crop/test/nodule/n0962/
   creating: ../split_node21_sets/crop/test/nodule/n0105/
   creating: ../split_node21_sets/crop/test/nodule/n0568/
   creating: ../split_node21_sets/crop/test/nodule/n0550/
   creating: ../split_node21_sets/crop/test/nodule/n0306/
   creating: ../split_node21_sets/crop/test/nodule/n0908/
   creating: ../split_node21_sets/crop/test/nodule/n1012/
   creating: ../split_node21_sets/crop/test/nodule/n0709/
   creating: ../split_node21_sets/crop/test/nodule/n0399/
   creating: ../split_node21_sets/crop/test/nodule/n1041/
   creating: ../split_node21_sets/crop/test/nodule/n0707/
   creating: ../split_node21_sets/crop/test/nodule/n1048/
   creating: ../split_node21_sets/crop/test/nodule/n0952/
   creating: ../split_node21_sets/crop/test/nodule/n0532/
   creating: ../split_node21_sets/crop/test/nodule/n0955/
   creating: ../split_node21_sets/crop/test/nodule/n0169/
   creating: ../split_node21_sets/crop/test/nodule/n0686/
   creating: ../split_node21_sets/crop/test/nodule/n0440/
   creating: ../split_node21_sets/crop/test/nodule/n0818/
   creating: ../split_node21_sets/crop/test/nodule/n0216/
   creating: ../split_node21_sets/crop/test/nodule/n0820/
   creating: ../split_node21_sets/crop/test/nodule/n0688/
   creating: ../split_node21_sets/crop/test/nodule/n0643/
   creating: ../split_node21_sets/crop/test/nodule/n0227/
   creating: ../split_node21_sets/crop/test/nodule/n0015/
   creating: ../split_node21_sets/crop/test/nodule/n0485/
   creating: ../split_node21_sets/crop/test/nodule/n0449/
   creating: ../split_node21_sets/crop/test/nodule/n0482/
   creating: ../split_node21_sets/crop/test/nodule/n0280/
   creating: ../split_node21_sets/crop/test/nodule/n0274/
   creating: ../split_node21_sets/crop/test/nodule/n0046/
   creating: ../split_node21_sets/crop/test/nodule/n0041/
   creating: ../split_node21_sets/crop/test/nodule/n0273/
   creating: ../split_node21_sets/crop/test/nodule/n0287/
   creating: ../split_node21_sets/crop/test/nodule/n0880/
   creating: ../split_node21_sets/crop/test/nodule/n0084/
   creating: ../split_node21_sets/crop/test/nodule/n0414/
   creating: ../split_node21_sets/crop/test/nodule/n0070/
   creating: ../split_node21_sets/crop/test/nodule/n0289/
   creating: ../split_node21_sets/crop/test/nodule/n0619/
   creating: ../split_node21_sets/crop/test/nodule/n1132/
   creating: ../split_node21_sets/crop/test/nodule/n0470/
   creating: ../split_node21_sets/crop/test/nodule/n0828/
   creating: ../split_node21_sets/crop/test/nodule/n0014/
   creating: ../split_node21_sets/crop/test/nodule/n0821/
   creating: ../split_node21_sets/crop/test/nodule/n1104/
   creating: ../split_node21_sets/crop/test/nodule/n0210/
   creating: ../split_node21_sets/crop/test/nodule/n0441/
   creating: ../split_node21_sets/crop/test/nodule/n0627/
   creating: ../split_node21_sets/crop/test/nodule/n0071/
   creating: ../split_node21_sets/crop/test/nodule/n0872/
   creating: ../split_node21_sets/crop/test/nodule/n0618/
   creating: ../split_node21_sets/crop/test/nodule/n0886/
   creating: ../split_node21_sets/crop/test/nodule/n0412/
   creating: ../split_node21_sets/crop/test/nodule/n0881/
   creating: ../split_node21_sets/crop/test/nodule/n0286/
   creating: ../split_node21_sets/crop/test/nodule/n0424/
   creating: ../split_node21_sets/crop/test/nodule/n0040/
   creating: ../split_node21_sets/crop/test/nodule/n0281/
   creating: ../split_node21_sets/crop/test/nodule/n0091/
   creating: ../split_node21_sets/crop/test/nodule/n0062/
   creating: ../split_node21_sets/crop/test/nodule/n0868/
   creating: ../split_node21_sets/crop/test/nodule/n0261/
   creating: ../split_node21_sets/crop/test/nodule/n0053/
   creating: ../split_node21_sets/crop/test/nodule/n0651/
   creating: ../split_node21_sets/crop/test/nodule/n0804/
   creating: ../split_node21_sets/crop/test/nodule/n0490/
   creating: ../split_node21_sets/crop/test/nodule/n0452/
   creating: ../split_node21_sets/crop/test/nodule/n0660/
   creating: ../split_node21_sets/crop/test/nodule/n0009/
   creating: ../split_node21_sets/crop/test/nodule/n0667/
   creating: ../split_node21_sets/crop/test/nodule/n0455/
   creating: ../split_node21_sets/crop/test/nodule/n0031/
   creating: ../split_node21_sets/crop/test/nodule/n1117/
   creating: ../split_node21_sets/crop/test/nodule/n0409/
   creating: ../split_node21_sets/crop/test/nodule/n0436/
   creating: ../split_node21_sets/crop/test/nodule/n0856/
   creating: ../split_node21_sets/crop/test/nodule/n0431/
   creating: ../split_node21_sets/crop/test/nodule/n0894/
   creating: ../split_node21_sets/crop/test/nodule/n0893/
   creating: ../split_node21_sets/crop/test/nodule/n0632/
   creating: ../split_node21_sets/crop/test/nodule/n0256/
   creating: ../split_node21_sets/crop/test/nodule/n0692/
   creating: ../split_node21_sets/crop/test/nodule/n0030/
   creating: ../split_node21_sets/crop/test/nodule/n1129/
   creating: ../split_node21_sets/crop/test/nodule/n0233/
   creating: ../split_node21_sets/crop/test/nodule/n1118/
   creating: ../split_node21_sets/crop/test/nodule/n1120/
   creating: ../split_node21_sets/crop/test/nodule/n0462/
   creating: ../split_node21_sets/crop/test/nodule/n0805/
   creating: ../split_node21_sets/crop/test/nodule/n0510/
   creating: ../split_node21_sets/crop/test/nodule/n0346/
   creating: ../split_node21_sets/crop/test/nodule/n0948/
   creating: ../split_node21_sets/crop/test/nodule/n0180/
   creating: ../split_node21_sets/crop/test/nodule/n0341/
   creating: ../split_node21_sets/crop/test/nodule/n0946/
   creating: ../split_node21_sets/crop/test/nodule/n0383/
   creating: ../split_node21_sets/crop/test/nodule/n0713/
   creating: ../split_node21_sets/crop/test/nodule/n0941/
   creating: ../split_node21_sets/crop/test/nodule/n0189/
   creating: ../split_node21_sets/crop/test/nodule/n0142/
   creating: ../split_node21_sets/crop/test/nodule/n1090/
   creating: ../split_node21_sets/crop/test/nodule/n0526/
   creating: ../split_node21_sets/crop/test/nodule/n0714/
   creating: ../split_node21_sets/crop/test/nodule/n0740/
   creating: ../split_node21_sets/crop/test/nodule/n0129/
   creating: ../split_node21_sets/crop/test/nodule/n0581/
   creating: ../split_node21_sets/crop/test/nodule/n0543/
   creating: ../split_node21_sets/crop/test/nodule/n0924/
   creating: ../split_node21_sets/crop/test/nodule/n0544/
   creating: ../split_node21_sets/crop/test/nodule/n0518/
   creating: ../split_node21_sets/crop/test/nodule/n0940/
   creating: ../split_node21_sets/crop/test/nodule/n1096/
   creating: ../split_node21_sets/crop/test/nodule/n0382/
   creating: ../split_node21_sets/crop/test/nodule/n0340/
   creating: ../split_node21_sets/crop/test/nodule/n0172/
   creating: ../split_node21_sets/crop/test/nodule/n0982/
   creating: ../split_node21_sets/crop/test/nodule/n1098/
   creating: ../split_node21_sets/crop/test/nodule/n1053/
   creating: ../split_node21_sets/crop/test/nodule/n0511/
   creating: ../split_node21_sets/crop/test/nodule/n0175/
   creating: ../split_node21_sets/crop/test/nodule/n0949/
   creating: ../split_node21_sets/crop/test/nodule/n0777/
   creating: ../split_node21_sets/crop/test/nodule/n1038/
   creating: ../split_node21_sets/crop/test/nodule/n0748/
   creating: ../split_node21_sets/crop/test/nodule/n0784/
   creating: ../split_node21_sets/crop/test/nodule/n0589/
   creating: ../split_node21_sets/crop/test/nodule/n0746/
   creating: ../split_node21_sets/crop/test/nodule/n0574/
   creating: ../split_node21_sets/crop/test/nodule/n0110/
   creating: ../split_node21_sets/crop/test/nodule/n0580/
   creating: ../split_node21_sets/crop/test/nodule/n0913/
   creating: ../split_node21_sets/crop/test/normal/c2815/
   creating: ../split_node21_sets/crop/test/normal/c1832/
   creating: ../split_node21_sets/crop/test/normal/c0741/
   creating: ../split_node21_sets/crop/test/normal/c3554/
   creating: ../split_node21_sets/crop/test/normal/c3766/
   creating: ../split_node21_sets/crop/test/normal/c0913/
   creating: ../split_node21_sets/crop/test/normal/c3137/
   creating: ../split_node21_sets/crop/test/normal/c0119/
   creating: ../split_node21_sets/crop/test/normal/c3591/

In [30]:
!unzip ../split_node21/lung_seg.zip -d ../split_node21_sets/

Archive:  ../split_node21/lung_seg.zip
   creating: ../split_node21_sets/lung_seg/
  inflating: ../split_node21_sets/lung_seg/.DS_Store
  inflating: ../split_node21_sets/__MACOSX/lung_seg/._.DS_Store
   creating: ../split_node21_sets/lung_seg/test/
   creating: ../split_node21_sets/lung_seg/train/
  inflating: ../split_node21_sets/lung_seg/test/.DS_Store
  inflating: ../split_node21_sets/__MACOSX/lung_seg/test/._.DS_Store
  inflating: ../split_node21_sets/lung_seg/test/process_log.csv
   creating: ../split_node21_sets/lung_seg/test/nodule/
   creating: ../split_node21_sets/lung_seg/test/normal/
  inflating: ../split_node21_sets/lung_seg/train/process_log.csv
   creating: ../split_node21_sets/lung_seg/train/nodule/
   creating: ../split_node21_sets/lung_seg/train/normal/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0198/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0154/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0957/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0734/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0357/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1043/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1088/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0758/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0935/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0109/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1010/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0794/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0760/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0903/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0564/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0904/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0563/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0107/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0597/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1042/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0958/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0732/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0500/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0993/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0507/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0538/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0367/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0703/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0358/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1074/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0394/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0704/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0199/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0902/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0101/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1027/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0108/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0305/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1011/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1029/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0759/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0933/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0130/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0614/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0042/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0089/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0045/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0277/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0428/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0246/
  inflating: ../split_node21_sets/lung_seg/test/nodule/.DS_Store
  inflating: ../split_node21_sets/__MACOSX/lung_seg/test/nodule/._.DS_Store
   creating: ../split_node21_sets/lung_seg/test/nodule/n0622/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0279/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0020/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0444/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0682/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0824/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0027/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0678/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0029/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1130/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0075/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0849/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0411/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0278/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0876/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0240/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0072/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0429/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0885/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0847/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0285/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0427/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0271/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0088/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0225/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0825/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0489/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0442/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0026/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1100/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0684/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1107/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0021/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0493/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0800/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0838/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1122/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1114/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0469/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0809/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0207/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0663/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0253/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0059/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0891/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0853/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0050/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0434/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0601/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0206/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0808/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0837/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0691/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0830/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1123/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1124/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0801/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0855/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0432/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0056/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0852/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0297/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0051/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0864/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0093/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0299/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0060/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0404/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0582/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0576/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0911/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0929/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0916/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0318/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0547/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0311/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0123/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0781/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0920/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0578/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0772/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0927/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1069/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0514/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0980/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0513/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0177/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0942/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0141/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0373/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0717/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0989/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1067/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0945/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0380/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0522/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0374/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1094/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0146/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0125/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0541/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0773/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0787/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0780/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0546/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1032/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0570/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0789/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0321/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0944/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1095/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1059/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0988/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0372/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0716/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0149/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0182/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0176/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0718/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0972/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0388/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0338/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1013/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0931/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0556/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0764/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0567/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0998/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0396/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0739/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1049/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0166/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0730/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0192/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1047/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1078/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0962/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0105/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0568/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0550/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0306/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0908/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1012/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0709/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0399/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1041/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0707/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1048/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0952/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0532/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0955/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0169/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0686/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0440/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0818/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0216/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0820/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0688/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0643/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0227/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0015/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0485/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0449/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0482/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0280/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0274/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0046/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0041/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0273/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0287/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0880/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0084/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0414/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0070/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0289/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0619/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1132/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0470/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0828/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0014/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0821/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1104/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0210/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0441/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0627/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0071/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0872/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0618/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0886/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0412/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0881/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0286/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0424/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0040/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0281/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0091/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0062/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0868/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0261/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0053/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0651/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0804/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0490/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0452/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0660/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0009/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0667/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0455/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0031/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1117/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0409/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0436/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0856/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0431/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0894/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0893/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0632/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0256/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0692/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0030/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1129/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0233/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1118/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1120/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0462/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0805/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0510/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0346/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0948/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0180/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0341/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0946/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0383/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0713/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0941/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0189/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0142/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1090/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0526/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0714/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0740/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0129/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0581/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0543/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0924/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0544/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0518/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0940/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1096/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0382/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0340/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0172/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0982/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1098/
   creating: ../split_node21_sets/lung_seg/test/nodule/n1053/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0511/
   creating: ../split_node21_sets/lung_seg/test/nodule/n0175/

In [ ]:
!rm -rf ../split_node21_sets/__MACOSX/

In [33]:
import os
import shutil
import pandas as pd
from pathlib import Path

# Configure these paths
BASE_PATH = "../split_node21_sets/crop"
# BASE_PATH = "../split_node21_sets/lung_seg"
# BASE_PATH = "../split_node21_sets/arch_seg"  # Path to your arch_seg folder
MAPPING_CSV = "../split_node21_sets/mapping.csv"  # Path to your mapping CSV file

print("Directory Reorganization Script")
print("=" * 40)

# Read the mapping CSV
try:
    mapping_df = pd.read_csv(MAPPING_CSV)
    print(f"Loaded mapping CSV with {len(mapping_df)} entries")
except FileNotFoundError:
    print(f"Error: Could not find mapping CSV at {MAPPING_CSV}")
    exit()
except Exception as e:
    print(f"Error reading CSV: {e}")
    exit()

# Verify required columns exist
if 'dir_name' not in mapping_df.columns or 'orig_dataset' not in mapping_df.columns:
    print("Error: CSV must contain 'dir_name' and 'orig_dataset' columns")
    exit()

# Create a dictionary for quick lookups
dir_to_dataset = dict(zip(mapping_df['dir_name'], mapping_df['orig_dataset']))

base_path = Path(BASE_PATH)

# Check if base path exists
if not base_path.exists():
    print(f"Error: Base path {base_path} does not exist")
    exit()

# Show current structure
print("\nCurrent directory structure:")
for split in ['train', 'test']:
    split_path = base_path / split
    if split_path.exists():
        for category in ['nodule', 'normal']:
            category_path = split_path / category
            if category_path.exists():
                dirs = [d.name for d in category_path.iterdir() if d.is_dir()]
                print(f"  {category_path}: {len(dirs)} directories")
                if dirs:
                    print(f"    Examples: {dirs[:3]}{'...' if len(dirs) > 3 else ''}")

# Process both train and test folders
for split in ['train', 'test']:
    split_path = base_path / split
    if not split_path.exists():
        print(f"Warning: {split_path} does not exist, skipping...")
        continue
        
    # Process both nodule and normal folders
    for category in ['nodule', 'normal']:
        category_path = split_path / category
        if not category_path.exists():
            print(f"Warning: {category_path} does not exist, skipping...")
            continue
        
        print(f"\nProcessing {category_path}...")
        
        # Get all directories in this category folder
        for item in category_path.iterdir():
            if item.is_dir():
                dir_name = item.name
                
                # Check if this directory is in our mapping
                if dir_name in dir_to_dataset:
                    orig_dataset = dir_to_dataset[dir_name]
                    
                    # Create the new path structure
                    new_base = base_path / orig_dataset / split / category
                    new_path = new_base / dir_name
                    
                    # Create the new directory structure if it doesn't exist
                    new_base.mkdir(parents=True, exist_ok=True)
                    
                    try:
                        # Move the entire directory
                        shutil.move(str(item), str(new_path))
                        print(f"Moved: {item} -> {new_path}")
                    except Exception as e:
                        print(f"Error moving {item}: {e}")
                else:
                    print(f"Warning: Directory '{dir_name}' not found in mapping CSV")

print("\nReorganization complete!")

# Show new structure
print("\nNew directory structure:")
for item in base_path.iterdir():
    if item.is_dir() and item.name not in ['train', 'test']:
        print(f"Dataset: {item.name}")
        for split in ['train', 'test']:
            split_path = item / split
            if split_path.exists():
                for category in ['nodule', 'normal']:
                    category_path = split_path / category
                    if category_path.exists():
                        count = len([d for d in category_path.iterdir() if d.is_dir()])
                        print(f"  {split}/{category}: {count} directories")

Directory Reorganization Script
========================================
Loaded mapping CSV with 3726 entries

Current directory structure:
  ../split_node21_sets/crop/train/nodule: 742 directories
    Examples: ['n0873', 'n0985', 'n0630']...
  ../split_node21_sets/crop/train/normal: 1839 directories
    Examples: ['c1320', 'c0950', 'c2196']...
  ../split_node21_sets/crop/test/nodule: 318 directories
    Examples: ['n0338', 'n0714', 'n0093']...
  ../split_node21_sets/crop/test/normal: 789 directories
    Examples: ['c2311', 'c1933', 'c3303']...

Processing ../split_node21_sets/crop/train/nodule...
Moved: ../split_node21_sets/crop/train/nodule/n0873 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0873
Moved: ../split_node21_sets/crop/train/nodule/n0985 -> ../split_node21_sets/crop/jsrt/train/nodule/n0985
Moved: ../split_node21_sets/crop/train/nodule/n0630 -> ../split_node21_sets/crop/jsrt/train/nodule/n0630
Moved: ../split_node21_sets/crop/train/nodule/n1126 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1126
Moved: ../split_node21_sets/crop/train/nodule/n0827 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0827
Moved: ../split_node21_sets/crop/train/nodule/n0492 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0492
Moved: ../split_node21_sets/crop/train/nodule/n0752 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0752
Moved: ../split_node21_sets/crop/train/nodule/n0467 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0467
Moved: ../split_node21_sets/crop/train/nodule/n0521 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0521
Moved: ../split_node21_sets/crop/train/nodule/n0294 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0294
Moved: ../split_node21_sets/crop/train/nodule/n0451 -> ../split_node21_sets/crop/padchest/train/nodule/n0451
Moved: ../split_node21_sets/crop/train/nodule/n0648 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0648
Moved: ../split_node21_sets/crop/train/nodule/n0575 -> ../split_node21_sets/crop/padchest/train/nodule/n0575
Moved: ../split_node21_sets/crop/train/nodule/n0722 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0722
Moved: ../split_node21_sets/crop/train/nodule/n0457 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0457
Moved: ../split_node21_sets/crop/train/nodule/n0635 -> ../split_node21_sets/crop/padchest/train/nodule/n0635
Moved: ../split_node21_sets/crop/train/nodule/n0258 -> ../split_node21_sets/crop/jsrt/train/nodule/n0258
Moved: ../split_node21_sets/crop/train/nodule/n0925 -> ../split_node21_sets/crop/padchest/train/nodule/n0925
Moved: ../split_node21_sets/crop/train/nodule/n0228 -> ../split_node21_sets/crop/padchest/train/nodule/n0228
Moved: ../split_node21_sets/crop/train/nodule/n0690 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0690
Moved: ../split_node21_sets/crop/train/nodule/n0640 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0640
Moved: ../split_node21_sets/crop/train/nodule/n0230 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0230
Moved: ../split_node21_sets/crop/train/nodule/n0077 -> ../split_node21_sets/crop/padchest/train/nodule/n0077
Moved: ../split_node21_sets/crop/train/nodule/n0857 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0857
Moved: ../split_node21_sets/crop/train/nodule/n0623 -> ../split_node21_sets/crop/padchest/train/nodule/n0623
Moved: ../split_node21_sets/crop/train/nodule/n0342 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0342
Moved: ../split_node21_sets/crop/train/nodule/n0812 -> ../split_node21_sets/crop/padchest/train/nodule/n0812
Moved: ../split_node21_sets/crop/train/nodule/n0117 -> ../split_node21_sets/crop/padchest/train/nodule/n0117
Moved: ../split_node21_sets/crop/train/nodule/n0316 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0316
Moved: ../split_node21_sets/crop/train/nodule/n0471 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0471
Moved: ../split_node21_sets/crop/train/nodule/n1057 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1057
Moved: ../split_node21_sets/crop/train/nodule/n0028 -> ../split_node21_sets/crop/padchest/train/nodule/n0028
Moved: ../split_node21_sets/crop/train/nodule/n0463 -> ../split_node21_sets/crop/jsrt/train/nodule/n0463
Moved: ../split_node21_sets/crop/train/nodule/n0527 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0527
Moved: ../split_node21_sets/crop/train/nodule/n0877 -> ../split_node21_sets/crop/padchest/train/nodule/n0877
Moved: ../split_node21_sets/crop/train/nodule/n0790 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0790
Moved: ../split_node21_sets/crop/train/nodule/n0769 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0769
Moved: ../split_node21_sets/crop/train/nodule/n0545 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0545
Moved: ../split_node21_sets/crop/train/nodule/n0022 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0022
Moved: ../split_node21_sets/crop/train/nodule/n0478 -> ../split_node21_sets/crop/padchest/train/nodule/n0478
Moved: ../split_node21_sets/crop/train/nodule/n1071 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1071
Moved: ../split_node21_sets/crop/train/nodule/n1127 -> ../split_node21_sets/crop/padchest/train/nodule/n1127
Moved: ../split_node21_sets/crop/train/nodule/n0811 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0811
Moved: ../split_node21_sets/crop/train/nodule/n0013 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0013
Moved: ../split_node21_sets/crop/train/nodule/n0761 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0761
Moved: ../split_node21_sets/crop/train/nodule/n1025 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1025
Moved: ../split_node21_sets/crop/train/nodule/n1068 -> ../split_node21_sets/crop/jsrt/train/nodule/n1068
Moved: ../split_node21_sets/crop/train/nodule/n0079 -> ../split_node21_sets/crop/jsrt/train/nodule/n0079
Moved: ../split_node21_sets/crop/train/nodule/n0973 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0973
Moved: ../split_node21_sets/crop/train/nodule/n0486 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0486
Moved: ../split_node21_sets/crop/train/nodule/n1105 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1105
Moved: ../split_node21_sets/crop/train/nodule/n0043 -> ../split_node21_sets/crop/padchest/train/nodule/n0043
Moved: ../split_node21_sets/crop/train/nodule/n0331 -> ../split_node21_sets/crop/padchest/train/nodule/n0331
Moved: ../split_node21_sets/crop/train/nodule/n0391 -> ../split_node21_sets/crop/padchest/train/nodule/n0391
Moved: ../split_node21_sets/crop/train/nodule/n0443 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0443
Moved: ../split_node21_sets/crop/train/nodule/n0143 -> ../split_node21_sets/crop/padchest/train/nodule/n0143
Moved: ../split_node21_sets/crop/train/nodule/n0751 -> ../split_node21_sets/crop/jsrt/train/nodule/n0751
Moved: ../split_node21_sets/crop/train/nodule/n0221 -> ../split_node21_sets/crop/padchest/train/nodule/n0221
Moved: ../split_node21_sets/crop/train/nodule/n0293 -> ../split_node21_sets/crop/jsrt/train/nodule/n0293
Moved: ../split_node21_sets/crop/train/nodule/n0397 -> ../split_node21_sets/crop/padchest/train/nodule/n0397
Moved: ../split_node21_sets/crop/train/nodule/n0494 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0494
Moved: ../split_node21_sets/crop/train/nodule/n1091 -> ../split_node21_sets/crop/jsrt/train/nodule/n1091
Moved: ../split_node21_sets/crop/train/nodule/n0573 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0573
Moved: ../split_node21_sets/crop/train/nodule/n1000 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1000
Moved: ../split_node21_sets/crop/train/nodule/n1005 -> ../split_node21_sets/crop/jsrt/train/nodule/n1005
Moved: ../split_node21_sets/crop/train/nodule/n0719 -> ../split_node21_sets/crop/jsrt/train/nodule/n0719
Moved: ../split_node21_sets/crop/train/nodule/n0193 -> ../split_node21_sets/crop/padchest/train/nodule/n0193
Moved: ../split_node21_sets/crop/train/nodule/n0840 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0840
Moved: ../split_node21_sets/crop/train/nodule/n0633 -> ../split_node21_sets/crop/jsrt/train/nodule/n0633
Moved: ../split_node21_sets/crop/train/nodule/n0064 -> ../split_node21_sets/crop/padchest/train/nodule/n0064
Moved: ../split_node21_sets/crop/train/nodule/n0226 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0226
Moved: ../split_node21_sets/crop/train/nodule/n0542 -> ../split_node21_sets/crop/padchest/train/nodule/n0542
Moved: ../split_node21_sets/crop/train/nodule/n0314 -> ../split_node21_sets/crop/padchest/train/nodule/n0314
Moved: ../split_node21_sets/crop/train/nodule/n0836 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0836
Moved: ../split_node21_sets/crop/train/nodule/n0405 -> ../split_node21_sets/crop/padchest/train/nodule/n0405
Moved: ../split_node21_sets/crop/train/nodule/n0923 -> ../split_node21_sets/crop/padchest/train/nodule/n0923
Moved: ../split_node21_sets/crop/train/nodule/n0802 -> ../split_node21_sets/crop/padchest/train/nodule/n0802
Moved: ../split_node21_sets/crop/train/nodule/n0822 -> ../split_node21_sets/crop/jsrt/train/nodule/n0822
Moved: ../split_node21_sets/crop/train/nodule/n1056 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1056
Moved: ../split_node21_sets/crop/train/nodule/n0245 -> ../split_node21_sets/crop/jsrt/train/nodule/n0245
Moved: ../split_node21_sets/crop/train/nodule/n0835 -> ../split_node21_sets/crop/padchest/train/nodule/n0835
Moved: ../split_node21_sets/crop/train/nodule/n0585 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0585
Moved: ../split_node21_sets/crop/train/nodule/n0926 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0926
Moved: ../split_node21_sets/crop/train/nodule/n0621 -> ../split_node21_sets/crop/jsrt/train/nodule/n0621
Moved: ../split_node21_sets/crop/train/nodule/n0768 -> ../split_node21_sets/crop/jsrt/train/nodule/n0768
Moved: ../split_node21_sets/crop/train/nodule/n0268 -> ../split_node21_sets/crop/padchest/train/nodule/n0268
Moved: ../split_node21_sets/crop/train/nodule/n0888 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0888
Moved: ../split_node21_sets/crop/train/nodule/n0215 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0215
Moved: ../split_node21_sets/crop/train/nodule/n0615 -> ../split_node21_sets/crop/padchest/train/nodule/n0615
Moved: ../split_node21_sets/crop/train/nodule/n0323 -> ../split_node21_sets/crop/padchest/train/nodule/n0323
Moved: ../split_node21_sets/crop/train/nodule/n0439 -> ../split_node21_sets/crop/padchest/train/nodule/n0439
Moved: ../split_node21_sets/crop/train/nodule/n0017 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0017
Moved: ../split_node21_sets/crop/train/nodule/n0052 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0052
Moved: ../split_node21_sets/crop/train/nodule/n0798 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0798
Moved: ../split_node21_sets/crop/train/nodule/n1045 -> ../split_node21_sets/crop/padchest/train/nodule/n1045
Moved: ../split_node21_sets/crop/train/nodule/n0930 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0930
Moved: ../split_node21_sets/crop/train/nodule/n0322 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0322
Moved: ../split_node21_sets/crop/train/nodule/n0204 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0204
Moved: ../split_node21_sets/crop/train/nodule/n0044 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0044
Moved: ../split_node21_sets/crop/train/nodule/n0681 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0681
Moved: ../split_node21_sets/crop/train/nodule/n1007 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1007
Moved: ../split_node21_sets/crop/train/nodule/n0300 -> ../split_node21_sets/crop/padchest/train/nodule/n0300
Moved: ../split_node21_sets/crop/train/nodule/n0155 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0155
Moved: ../split_node21_sets/crop/train/nodule/n0557 -> ../split_node21_sets/crop/padchest/train/nodule/n0557
Moved: ../split_node21_sets/crop/train/nodule/n0487 -> ../split_node21_sets/crop/padchest/train/nodule/n0487
Moved: ../split_node21_sets/crop/train/nodule/n0829 -> ../split_node21_sets/crop/jsrt/train/nodule/n0829
Moved: ../split_node21_sets/crop/train/nodule/n0598 -> ../split_node21_sets/crop/padchest/train/nodule/n0598
Moved: ../split_node21_sets/crop/train/nodule/n0415 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0415
Moved: ../split_node21_sets/crop/train/nodule/n1121 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1121
Moved: ../split_node21_sets/crop/train/nodule/n0586 -> ../split_node21_sets/crop/padchest/train/nodule/n0586
Moved: ../split_node21_sets/crop/train/nodule/n1035 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1035
Moved: ../split_node21_sets/crop/train/nodule/n0977 -> ../split_node21_sets/crop/padchest/train/nodule/n0977
Moved: ../split_node21_sets/crop/train/nodule/n0095 -> ../split_node21_sets/crop/padchest/train/nodule/n0095
Moved: ../split_node21_sets/crop/train/nodule/n0652 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0652
Moved: ../split_node21_sets/crop/train/nodule/n0983 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0983
Moved: ../split_node21_sets/crop/train/nodule/n0744 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0744
Moved: ../split_node21_sets/crop/train/nodule/n1052 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1052
Moved: ../split_node21_sets/crop/train/nodule/n0074 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0074
Moved: ../split_node21_sets/crop/train/nodule/n0747 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0747
Moved: ../split_node21_sets/crop/train/nodule/n0174 -> ../split_node21_sets/crop/padchest/train/nodule/n0174
Moved: ../split_node21_sets/crop/train/nodule/n0103 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0103
Moved: ../split_node21_sets/crop/train/nodule/n0270 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0270
Moved: ../split_node21_sets/crop/train/nodule/n1028 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1028
Moved: ../split_node21_sets/crop/train/nodule/n0803 -> ../split_node21_sets/crop/padchest/train/nodule/n0803
Moved: ../split_node21_sets/crop/train/nodule/n0645 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0645
Moved: ../split_node21_sets/crop/train/nodule/n0203 -> ../split_node21_sets/crop/jsrt/train/nodule/n0203
Moved: ../split_node21_sets/crop/train/nodule/n0267 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0267
Moved: ../split_node21_sets/crop/train/nodule/n0147 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0147
Moved: ../split_node21_sets/crop/train/nodule/n0137 -> ../split_node21_sets/crop/padchest/train/nodule/n0137
Moved: ../split_node21_sets/crop/train/nodule/n0689 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0689
Moved: ../split_node21_sets/crop/train/nodule/n0595 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0595
Moved: ../split_node21_sets/crop/train/nodule/n0992 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0992
Moved: ../split_node21_sets/crop/train/nodule/n0116 -> ../split_node21_sets/crop/padchest/train/nodule/n0116
Moved: ../split_node21_sets/crop/train/nodule/n0897 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0897
Moved: ../split_node21_sets/crop/train/nodule/n0255 -> ../split_node21_sets/crop/padchest/train/nodule/n0255
Moved: ../split_node21_sets/crop/train/nodule/n0997 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0997
Moved: ../split_node21_sets/crop/train/nodule/n0073 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0073
Moved: ../split_node21_sets/crop/train/nodule/n0328 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0328
Moved: ../split_node21_sets/crop/train/nodule/n0887 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0887
Moved: ../split_node21_sets/crop/train/nodule/n0741 -> ../split_node21_sets/crop/jsrt/train/nodule/n0741
Moved: ../split_node21_sets/crop/train/nodule/n0448 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0448
Moved: ../split_node21_sets/crop/train/nodule/n0793 -> ../split_node21_sets/crop/padchest/train/nodule/n0793
Moved: ../split_node21_sets/crop/train/nodule/n0483 -> ../split_node21_sets/crop/padchest/train/nodule/n0483
Moved: ../split_node21_sets/crop/train/nodule/n1089 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1089
Moved: ../split_node21_sets/crop/train/nodule/n1055 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1055
Moved: ../split_node21_sets/crop/train/nodule/n0775 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0775
Moved: ../split_node21_sets/crop/train/nodule/n0055 -> ../split_node21_sets/crop/padchest/train/nodule/n0055
Moved: ../split_node21_sets/crop/train/nodule/n1040 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1040
Moved: ../split_node21_sets/crop/train/nodule/n0650 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0650
Moved: ../split_node21_sets/crop/train/nodule/n0666 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0666
Moved: ../split_node21_sets/crop/train/nodule/n1017 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1017
Moved: ../split_node21_sets/crop/train/nodule/n0712 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0712
Moved: ../split_node21_sets/crop/train/nodule/n1092 -> ../split_node21_sets/crop/jsrt/train/nodule/n1092
Moved: ../split_node21_sets/crop/train/nodule/n1083 -> ../split_node21_sets/crop/chestxray14/train/nodule/n1083
Moved: ../split_node21_sets/crop/train/nodule/n1072 -> ../split_node21_sets/crop/padchest/train/nodule/n1072
Moved: ../split_node21_sets/crop/train/nodule/n0312 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0312
Moved: ../split_node21_sets/crop/train/nodule/n0231 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0231
Moved: ../split_node21_sets/crop/train/nodule/n0537 -> ../split_node21_sets/crop/padchest/train/nodule/n0537
Moved: ../split_node21_sets/crop/train/nodule/n0523 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0523
Moved: ../split_node21_sets/crop/train/nodule/n0779 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0779
Moved: ../split_node21_sets/crop/train/nodule/n0975 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0975
Moved: ../split_node21_sets/crop/train/nodule/n0964 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0964
Moved: ../split_node21_sets/crop/train/nodule/n0302 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0302
Moved: ../split_node21_sets/crop/train/nodule/n0260 -> ../split_node21_sets/crop/padchest/train/nodule/n0260
Moved: ../split_node21_sets/crop/train/nodule/n0705 -> ../split_node21_sets/crop/padchest/train/nodule/n0705
Moved: ../split_node21_sets/crop/train/nodule/n0530 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0530
Moved: ../split_node21_sets/crop/train/nodule/n0854 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0854
Moved: ../split_node21_sets/crop/train/nodule/n0685 -> ../split_node21_sets/crop/padchest/train/nodule/n0685
Moved: ../split_node21_sets/crop/train/nodule/n0236 -> ../split_node21_sets/crop/jsrt/train/nodule/n0236
Moved: ../split_node21_sets/crop/train/nodule/n0450 -> ../split_node21_sets/crop/padchest/train/nodule/n0450
Moved: ../split_node21_sets/crop/train/nodule/n0654 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0654
Moved: ../split_node21_sets/crop/train/nodule/n1051 -> ../split_node21_sets/crop/jsrt/train/nodule/n1051
Moved: ../split_node21_sets/crop/train/nodule/n0539 -> ../split_node21_sets/crop/padchest/train/nodule/n0539
Moved: ../split_node21_sets/crop/train/nodule/n0272 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0272
Moved: ../split_node21_sets/crop/train/nodule/n0076 -> ../split_node21_sets/crop/chestxray14/train/nodule/n0076